name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: pnpm install
        run: |
          pnpm install

      - name: pnpm test
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pnpm package
          pnpm lint
          pnpm exec tsc
          pnpm test
